---
title: wank
---

```{r iinstall, echo=FALSE}
library(googlesheets4)
library(gt)
library(tidyverse)
library(lubridate)
library(dplyr)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/1C03QNEp_foGSRXncI68DKEpIC1NqLDhv1TffH3hQCA8/edit?usp=sharing", sheet = "draft1")
```

::: column-screen-right
```{r transformations, echo=FALSE}
# Function for conditional text transformation
conditional_transform_fn <- function(icon_name) {
  function(x) {
    ifelse(is.na(x) | x == "", "",
           ifelse(grepl("FUTURE", x), fontawesome::fa(icon_name, fill_opacity = 0.25),
                  glue::glue("<a href = {'http://researchmethods.littlemonkeylab.com'}{x}{'.html'}>{fontawesome::fa(icon_name)}</a>")
           )
    )
  }
}

# Main Code
d |>
  mutate(
    week = ifelse(is.na(week), "", week),
    date = ifelse(
      is.na(date) | date == "", 
      "", 
      {
        temp_date <- as.Date(date, format="%m/%d/%Y")
        paste(wday(temp_date, label = TRUE, abbr = FALSE), ", ", format(temp_date, "%d %B"))
      }
    )
  ) |>
  gt() |>
  text_transform(cells_body(columns = c(prepare)), fn = conditional_transform_fn("binoculars")) |>
  text_transform(cells_body(columns = c(slides)), fn = conditional_transform_fn("person-chalkboard")) |>
  text_transform(cells_body(columns = c(lab)), fn = conditional_transform_fn("users")) |>
  text_transform(cells_body(columns = c(reading)), fn = conditional_transform_fn("bookmark")) |>
  text_transform(cells_body(columns = c(minidiss)), fn = conditional_transform_fn("book")) |>
  sub_missing(columns = c(date, what, topic, notes), missing_text = "") |>
  cols_align(align = "center", columns = c(week, prepare, slides, lab, reading, minidiss)) |>
  cols_align(align = "left", columns = c(date, what, topic, notes)) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(week, prepare, slides, lab, reading, minidiss)
    )
  ) |>
  # Setting text size for 'notes' column
  
  tab_style(
    style = htmltools::css(font_size = "0.9em"),
    locations = cells_body(
      columns = c(notes)
    )
  ) |>
  
  tab_style(
    style = htmltools::css(font_size = "0.75em"),
    locations = cells_body(
      columns = everything()
    )
  ) |>
  
  # Setting column widths for specified columns
  tab_style(
    style = htmltools::css(width = "5%"),
    locations = cells_body(
      columns = c(prepare, slides, lab, reading, minidiss)
    )
  )

```
:::
