---
title: "Research Methods in Psychology"
subtitle: "Goldsmiths Year 2 - Research Methods Practical"
details: |
  PS52007D • 2023/4<br>Department of Psychology<br>Goldsmiths, University of London
sidebar: false
toc: false
page-layout: full
# format:
  # html:
    # template-partials:
      # - html/home/title-block.html
course-logo: images/LMLLOGO.png
---

# Course Information

::: {style="width:600px"}
| Instructor                                                                                                 | Course                                                   |
|------------------------------------------------------------------------------------------------------------|----------------------------------------------------------|
| <i class="fas fa-user"></i> Dr. Gordon Wright                                                              | <i class="far fa-calendar"></i> Lecture: Mondays         |
| <i class="fas fa-university"></i> Whitehead 200/1                                                          | <i class="fa fa-map-marker-alt"></i> PSH LG02 10-11am    |
| <i class="fas fa-talk"></i> Office Hours: Monday Afternoon time TBC                                        | <i class="far fa-calendar-alt"></i> Labs : Tuesdays      |
| <i class="fas fa-envelope"></i> [{{< var instructor.email >}}](mailto:%7B%7B%3C%20var%20email%20%3E%7D%7D) | <i class="far fa-clock"></i> See your personal timetable |
| <i class="fab fa-twitter"></i> [\@DrDeception](https://twitter.com/drdeception)                            |                                                          |
:::

# Attendance / class recording

You should plan to attend lectures and labs in person - attendance is
taken at all timetabled sessions! In-person attendance is optimal as we
will spend a lot of time working on your Mini-Dissertations and research
skills. The best idea is to 'keep up, don't catch up' but of course,
life happens. We know this and will try to help you whenever we can, but
we can't offer Extenuating Circumstances or mark you as present etc. You
should try to update your Personal Tutor, Lab Tutor and research group
members if you anticipate missing a session.

Lab Sessions are NOT recorded either. Any activities or resources will
be available via the VLE or this site, but it is your responsibility to
keep abreast of your group progress and to catch up if necessary.

# Learning Objectives

Students who successfully complete this module will be able to:

-   Show a critical understanding of research design and methodology
-   Design, conduct, analyse, interpret and disseminate psychological
    research
-   Understand the conceptual and historical issues concerned with
    psychology as a science and area of practical application
-   Demonstrate valuable time-management and collaborative
    project-management skills and proficiencies
-   Reflect on their own learning, skill development and metacognition,
    preparing them for the final year dissertation

# Pep Talk!

You might be intimidated by the idea of 'Research Methods' or the
prospect of running a piece of real research. This is understandable,
but really not necessary.

If you are able to manage your independent study, attend labs and view
these sessions as 'working sessions', you'll do just fine. By viewing
your Lab Tutor as your 'Supervisor' and developing a dialogue with them
each week, updating them with successes AND problems, you will get the
best support available. Please don't panic, and please don't stay quiet.
The sooner you address any problems or issues, the sooner we can fix
them and get you back on track.

The biggest tip I can offer is around note-taking. Keeping good notes, a
'lab notebook' if you like, and gradually building a source of 'truth',
is crucial to success on this module. We will be supporting this, but I
encourage you to find a process that works for you. Make sure that your
notes are available AT ALL TIMES. Use a cloud-based system (University
Microsoft resources such as OneDrive and OneNote are free). Make sure to
back up your drafts and notes. Your Lab Tutors will ask to see your
notes to see what you have done to solve any problems you face, or to
see the current 'status' of your project, such as your Design. Please
think how this will pay off in the future, as once you've set it down
and had a thumbs-up from your Lab Tutor, you can rely upon that
information as 'truth' and you don't need to puzzle over aspects of your
study any further.

**I promise, you can do this** Turn up, use your labs and independent
study time wisely, and don't be afraid of making mistakes. Now is the
time to make mistakes, and if you DON'T make mistakes, you aren't doing
it right!

## Expectation management

The teaching team on the module are here because Psychological Research
is one of our passions. We teach it to you because we know it to a
hugely valuable skill, not just a programme requirement. We understand
that you might not immediately think it's going to be fun, or useful,
but we aren't going to continually try to coax you into activity. If
necessary, consider how the skills involved will be important for your
final grade, for your future career path, or for your general
intellectual development. Then throw yourself into it.

The bare minimum expectation is to attend Lectures and Labs, to engage
with the content, and to allocate independent study hours each and every
week. How many hours will be a decision you need to make for yourself,
but they are required EVERY week. This module is 25% of the year in
terms of module weight, 29% of your year grade, and when combined with
your final year dissertation, research contributes 50% of your final
grade.

It is easy to get sidetracked with Essays during the course of the term.
Please consider that those essays contribute 15% of a 15 credit module.
The Critical Proposal is worth double that for starters, and your
Mini-Dissertation is worth 10X more than any individual essay.
Allocating too much time to the 5 essays and falling behind on your
Mini-Dissertation is a really poor idea.

Materials on the VLE will be considered the 'baseline' and you should
familiarise yourself with what is available there - it will be
everything you need to do really well. We shall be offering 'extras' -
resources that will support further exploration of a topic, developing
further skills, or just interesting added-value content, you will find
this under 'DangerZone' - these are optional, and if you wish to add
anything to these, or suggest some content, please let me know - always
happy to help!

On this site, resources may include short self-assessment quizzes.
Answers are NOT tracked, so use these to test your comprehension, or
identify areas for focus.

> **Why quiz at all?** Research shows that giving small quizzes
> throughout a class can dramatically help with *retention*. It's a
> phenomenon known as the "retrieval effect" - basically, you have to
> *practice* remembering things, otherwise your brain won't remember
> them. The phenomenon and research on it is explained in detail in the
> book ["Make It Stick: The Science of Successful
> Learning,"](https://www.hup.harvard.edu/catalog.php?isbn=9780674729018)
> by Brown, Roediger, and McDaniel.

## Teamwork

I bet you just let out a sigh of disgust. Everyone does at the thought
of working as a group. But... Do you know the first question on NHS
Clinical Doctorate reference requests? Or the first thing that employers
usually ask for in Reference Request templates and questionnaires?

"To what extent is the applicant able to work as part of a team?"

I kid you not. And if you can't operate effectively in a team, we have
to say so. It's a silly way to miss out on a job. View the process of
team work as something that you actively allocate time to. Develop a
process. Communicate. Plan. Evaluate.

In this module, we suggest a process based in Software Development,
called Scrum. There are many variants and nuances, but the key component
is a Stand-Up meeting. We propose that you use the first 15 minutes of
EVERY lab to run such a meeting. Each team member has 1-2 minutes (VERY
SHORT) to cover 3 topics. 1- What did you do last week? 2 - What are you
going to do in today's lab/this week? 3 - Do you anticipate any
obstacles or problems?

This ensures accountability towards group goals, allows you to clearly
identify areas you need to focus on, and to be ready to ask your Lab
Tutor any questions that may obstruct your progress. Each week I will be
giving a set of reasonable objectives to help you work out where you
could/should be. These are obviously flexible, but you should look to
make forward progress each and every week.

If you choose to use an alternative system to manage your team or your
time, fine. But it cannot be replaced with nothing. Your Lab Tutor will
be asking to see your plans, and see how you may have allocated tasks or
responsibilities. It may sound like a burden, but this is what you will
likely have to do with your supervisor next year, and certainly you'll
need these skills in later life. It takes a few minutes a week, but
could save you DAYS!

# Grades

## Passing the module.

Every year a handful of people fail the module. This is usually because
they don't submit one of the three pieces of work. If you attend the
labs, and follow the suggested activities, you will pass. Simple as
that. If you submit an Ethics Application, collect data, analyse it
using a 2x2 ANOVA, and write up a complete APA format report, with
supplementary Open Materials and Open Data, you WILL pass. So the
question is really...

## How to improve your grade

The Mini-Dissertation has roughly 27 key moving parts. It's easy to deal
with them all over the course of 20 weeks. But by approaching each as an
opportunity to draft, revise and refine, you will be continually
building marks. First drafts or incomplete elements get poor marks -
simple as that. Use the resources as a guide, don't miss anything out,
give yourself time. If anything is unclear, ask your Lab Tutor, or ask
me. There are no hidden traps on this module. It's just do some research
within the constraints described, and write it up in APA format.

## Textbooks

The library reading list includes textbooks and resources with a
preference for those that are freely available and online, either via
the library website, or cost-free on the internet. We shall be sharing
lots of resources we have developed, and signposting other free
resources. There really is NO NEED to pay for access to other materials
(unless you want to), but there is usually no shortcut you can pay for.
If resources don't exist, ask for them.

Finding a consistent textbook that you use and trust is highly
recommended - if in doubt have a poke around on the Library Reading list
and find one you like. A consistent voice is better than just googling a
question and hearing different takes from numerous different sources.

I shall be signposting Open Educational Resources that have good take on
any topic, and maybe even tailoring those resources to the year. Please
consider using `Hypothes.is` to track your resources, and to share them
with the group using the `PS52007D group`

|                                                                         |                          |                                   |
|-------------------------------------------------------------------------|--------------------------|-----------------------------------|
| [Introduction to Modern Statistics](https://openintro-ims.netlify.app/) | Çetinkaya-Rundel, Hardin | OpenIntro Inc., 1st Edition, 2021 |
