---
title: "Mini-Dissertation Write-up Guide"
subtitle: "Part 09 - Pre-Submission Checking"
mainfont: "Atkinson Hyperlegible"
author: 
  - name: "Dr. Gordon Wright"
    orcid: 0000-0001-9424-5743
    email: g.wright@gold.ac.uk
date: "03/12/2024"
date-format: long
license: "CC BY-NC-SA"
editor: 
  markdown: 
    wrap: sentence
---

# Submission information for your Mini-Dissertations

::: {.callout-caution appearance="simple" icon="false"}
## In this document, we shall cover the following:

[General pointers to review and recap materials]

[General pointers on Supplementary Materials (Open Data, Open Materials, Reflective Account)](#general-pointers-on-supplementary-materials-open-data-open-materials-reflective-account)

[Open Data requirements]

[Open Materials requirements]

[Reflective Account requirements]

[Closing points to remember]
:::

## General pointers to review and recap materials

Please take the time to listen to the recording of the Week 18 lecture - which reviewed and summarised the extensive resources of various types that you can use to support the writing up phase of your Mini-Dissertations.

-   [Rubrics, example MDs, and templates - including the opinionated APA word document template (i.e. it has comments THROUGHOUT!)](https://learn.gold.ac.uk/mod/folder/view.php?id=1237525)

-   [Analysis and stats support from Y1 & 2 - duplicated from Design & Analysis module](https://learn.gold.ac.uk/mod/folder/view.php?id=1266571)

-   [Lab 15 Worksheet - Setting up analysis](https://learn.gold.ac.uk/pluginfile.php/2013649/mod_book/chapter/93711/LabWorksheet15.pdf)

-   [Lab 17 Worksheet - Doing your analysis](https://learn.gold.ac.uk/pluginfile.php/2018065/mod_book/chapter/93859/Worksheet17.pdf)

-   [Lab 18 Worksheet - Some pointers on the Introduction](https://learn.gold.ac.uk/pluginfile.php/2019528/mod_book/chapter/94033/Lab%20Worksheet%2018.pdf)

## General pointers on Supplementary Materials (Open Data, Open Materials, Reflective Account) {#general-pointers-on-supplementary-materials-open-data-open-materials-reflective-account}

For your Mini-Dissertations, you should consider using all of the tools available to you to best communicate your research.
The Mini-Dissertation itself can include tables, figures and images/diagrams.
You should NOT include appendices unless you feel it important that a reader has material while they read your dissertation BUT it is too long or disruptive to have as an inline visual or table etc.
Lazy appendices filled with every little thing you can think of do not win marks.

Your Mini-Dissertation is incomplete if you do not submit Data, Materials or include a short reflective account after your references in your Mini-Dissertation document itself.

If you are pressed for time, a good job of these additions can be achieved in about an hour max.
It doesn't need to be a time-consuming exercise.

You will likely ask for examples that you can copy.
Well as this is an Open Science practice, there are numerous examples available (although not as many as you would necessarily hope for), and many are far from good.
I'll highlight a couple below.

Example of fairly perfunctory open data.
How useful do you find this addition to a paper on Duping Delight?
<https://osf.io/r96fc> .
Sure, it's good the data and syntax are given, but you've got to work really hard to work out what everything is.
They didn't even really fill out any of the website metadata to help readers.

A far more comprehensive delivery of the task - nothing fancy, a few word docs (that could have been put together) and a couple of .csv/R files.
Everything you could possibly really need.
From the Nosek Lab...
Any idea why that might be indicative?
<https://osf.io/347ck/>

::: callout-caution
## But where do I put the 17 pages of complete SPSS output?

There is no need to include complete SPSS output.
Please don't!

Relevant information from it should be reproduced (yes, reproduced) in your report or in your Open Data - [if you think it is useful or informative.]{.underline} If you are uncertain, this is a question that can be asked of your Lab Tutor or moi - as always.
:::

\newpage

## Open Data requirements

Open Data is the concept of making research data accessible to everyone, promoting transparency, reproducibility, and collaboration in research - all critical features of an Open Science.
In the field of psychology, sharing data is crucial for advancing scientific knowledge.
This guide will provide step-by-step instructions for creating an Open Data submission for a psychology research project such as the Mini-Dissertation (and your Final Year Dissertations for that matter!).

::: callout-important
## Important

It is a compulsory that you submit your data.
If you do not submit something, then your submission is not complete and the mark awarded will be impacted.

By taking the time to produce a clear Open Data submission, you will enhance the overall quality of your submission, and this will be reflected in your mark.
:::

1.  Prepare your data: Before submitting your data, ensure that it is well-organized, accurate, and complete.
    You might be fixated on doing the analysis, but in many ways, the way you treat and pre-process your data (prepare it for the analysis) is [even more]{.underline} critical to reliable results.

2.  This includes:

    a\.
    Cleaning and validating the data: Remove any errors, inconsistencies, or missing values.
    This may be down to participant error or a result of anything you might have done in this, your first data collection exercise (mistakes are to be EXPECTED! Don't hide them!).
    Make sure the data is properly formatted (an example here might be consistent decimal places, or labelling in your variable headers.

    b\.
    Anonymizing the data: To protect participants' privacy, remove any personally identifiable information (PII), such as names, addresses, or user generated codes.
    Replace these with unique identifiers, if necessary.
    This can be as simple as a number from 1 - n (where n is your total sample size).

3.  Create a data dictionary or codebook: A data dictionary is a simple document that describes the variables in your dataset, their definitions, units of measurement, and any coding schemes used, such as values for any categorised data e.g. gender (1 = female, 2 = male, 3 = prefer not to say).

    This will help others understand and use your data more effectively.
    Consider including the following information for each variable:

    a.  Variable name as it exists in your dataset
    b.  Variable description - what is the variable? Score on what measure of your Open Materials?
    c.  Data type (e.g., categorical, continuous, binary)
    d.  Units of measurement (if applicable, milliseconds, hours per day)
    e.  Consider count information, or summary information (mean, range etc)
    f.  Coding scheme (if applicable, 1 = strongly disagree, 2 = disagree etc.)

4.  Information on any pre-processing you performed:

    What were your decision rules on missing data or participant exclusion?
    Your data set can be the original data set which includes data you later do not analyse, or the data set that had undergone pre-processing and had had all the missing values removed...
    in either case, I want to know the process involved, so that I will be able to do it if I try to replicate your analysis!

5.  Choose a suitable format (or formats) for submission: In real research, you could host this on OSF.io or a similar data repository, but you are going to submit it as a supplementary file.
    Choose a format (or formats) that are usable.
    Ideally, I would like to be able to import your data directly, so it should be in a .csv, .xlsx, or .sav file, but Jamovi, R or equivalent is fine too.

    Any descriptive content (such as 3 or 4) could be in a pdf and submitted alongside the Mini-Dissertation (you can submit up to 5 files)

By following these guidelines, you will contribute to a more transparent and collaborative research environment in the field of psychology, ultimately promoting the advancement of scientific knowledge.

\newpage

## Open Materials requirements

An Open Materials submission is an essential part of transparent and reproducible research in psychology.
By providing a comprehensive account of your research materials, methods, and procedures, you enable others to understand, evaluate, and replicate your work.
This guide will walk you through the steps to create a robust Open Materials submission for your psychology research projects this year and next.

This works alongside your Methods section (and provides the tools you have described and referenced appropriately) in a nice 'ready to go' packet that is clearly navigable.

::: callout-important
## Important

It is a compulsory that you submit your materials.
If you do not submit something, then your submission is not complete and the mark awarded will be impacted.

By taking the time to produce a clear Open Materials submission, you will enhance the overall quality of your submission, and this will be reflected in your mark.
:::

1.  Organize your materials.
    Start by gathering all the materials you used in your research project - the things you sourced and produced to run the study.
    This includes, but is not limited to:

    a.  Stimuli (e.g., images, videos, audio recordings, or text)

    b.  Experimental software, code, or scripts

    c.  Data collection instruments (e.g., surveys, questionnaires, interview protocols)

    d.  Information, Consent, and Debriefing forms and confirmation of ethics approval (if you happen to have it)

    e.  Study protocols and instructions

    f.  Data analysis scripts or code (unless you feel these sit more sensibly in the Open Data)

        You don't need to produce anything that you didn't use, and you can simply screengrab these if it proves easier.
        But try to think about whether there were things that were difficult to find for you.
        Don't be that researcher.
        Make sure anyone wishing to repeat your marvellous exploits has them at their fingertips.

2.  Document your methodology if necessary.
    For each material above, provide a description of its purpose and use in your research project if this is not immediately apparent.
    For example, it's important that you include your questionnaire measures - but is it your IV or your DV?
    Is it labelled?
    Have you included a brief note of which items were reverse scored?
    What range of responses were available to the participant?

    Describe the methodology you followed, including:

    a.  Study design (e.g., Repeated Measures, Mixed or Between-groups) - a measure could be used twice in a repeated measures design, or used to categorise your IV (e.g. Low/High X) in another design
    b.  Participants (e.g., demographic questions, recruitment process or adverts, sample size requirement, inclusion and exclusion criteria)
    c.  Procedure (e.g., task instructions, randomization schedule, counterbalancing)
    d.  Measures (e.g., dependent and independent variables, operational definitions)
    e.  anything else that you needed for your study!

3.  Anonymize your materials.
    Before sharing your materials, ensure all identifiable participant information is removed to protect privacy.
    And if your name is on anything, redact it for the purposes of an anonymous submission.

4.  Prepare your materials for sharing.
    Make sure your materials are user-friendly (e.g., text files, spreadsheets, PDFs).
    Try to show how proud you are of the materials you produced.
    If in doubt, a PDF allows you to control how a document will look and be confident it doesn't reformat.

5.  If your submission contains multiple documents, consider writing a README file or index to signpost the materials you are making available.

By following these steps, you can create a comprehensive and accessible Open Materials submission for your psychology research project, promoting transparency, reproducibility, and collaboration in the scientific community.

\newpage

## Reflective Account requirements

Reflective practice plays a critical role in enhancing learning and meta-learning, particularly for those engaging in empirical research in psychology and research methods.
By reflecting on the experiences, challenges, and successes encountered during a research project, individuals can develop a deeper understanding of their learning process, refine their research skills, and contribute more effectively to the broader scientific community.

::: callout-important
## Important

It is a compulsory that you submit a Reflective Account - it doesn't have to be long.
If you do not submit something, then your submission is not complete and the mark awarded will be impacted.

By taking the time to reflect on the Mini-Dissertation thoughtfully, you will enhance the overall quality of your submission, and this will be reflected in your mark.
This can be entirely personal, doesn't have to be positive, and might be geared around what you have learned with regards to how to go about your Final Year Dissertation (as a suggestion).

You [cannot]{.underline} win marks by describing all the difficulties you've experienced or how group work is awful and it's all Trevor's fault that you only got 7 participants, and you'll only work solo from here on out.
You engage with this modest requirement appropriately by discussing what you have learned about group work, and what processes you might put in place to improve the experience or outcome when you **next** have to deliver a complex piece of work under such circumstances.
:::

Embarking on a first empirical research project presents numerous opportunities for personal and professional growth, however, without a structured reflective process, these opportunities may go unrealized.

Furthermore, assume that this might be the most recent piece of group work you have performed when you sit in an interview for a job you [really]{.underline} want and the interviewer asks "So tell me about how you work in a team" \[insanely common interview question\].

This will be the most authentic experience you could draw upon, and delivering a piece of novel empirical research is something you may want to highlight to future employers (as well as your love of data analysis for developing novel insights etc) - you scoff, but once being data literate gives you a better chance of getting this job...

To maximize the benefits of reflective practice, consider the following guidance when reflecting on your first research project in psychology and research methods:

1.  Document your journey: You won't have kept a research journal throughout your project to record your thoughts, feelings, and observations - I do - it's priceless - it serves as a valuable resource for reflection, self-improvement, self-criticism (gently) and can provide insights into your decision-making and problem-solving processes that work - or don't.
    Consider it next year.
    But you can easily think about the key phases of the research process and which ones were positive at the time or in retrospect, or negative for that matter - or that you delivered on well (according to your own rules) or not.
    This is about you, and the 'you' now may not be the 'you' then.

2.  Ask critical questions of yourself: Reflect on key aspects of your Mini-Dissertation, such as the formulation of research questions, the selection of tools, the ethical considerations, and the interpretation of results.
    Ask yourself what worked well, what could have been improved, and what you learned from each experience - for example with regards to what you're going to do next year or in later life.

3.  Evaluate your learning process: Assess the development of your research skills, critical thinking abilities, and communication competencies.
    Identify areas where you excelled and areas that require further development.
    Consider setting specific goals for improvement and creating an action plan to achieve them - it's lovely to hear about these, and if we can help, we will!

4.  Explore the broader context: Consider how your research project fits within the larger field of psychology and research methods.
    Reflect on the implications of your findings for the scientific community, and identify potential avenues for future research.
    Or you could reflect on how you might have learned better, what would have been provided to allow for that?

5.  In Reflective accounts for Clinical practice (for example), you might often be asked to 'Seek feedback' or be 'observed' by your supervisor or trainer.
    You don't have to do this now, but what if your Lab Tutor were to give you feedback.
    What would they say?
    This is worth considering as you will be working closely with a supervisor next year, and thinking about how to optimise that relationship and the finite time you have with them is valuable!

6.  Synthesize and apply: Try to not just give a number of granular ideas..
    Step back.
    Is there a bigger picture perspective?
    Integrate the insights gained from reflection.
    Reflective practice fosters a healthy attitude where you think critically about your performance and make conscious, deliberate efforts to improve.
    That's all you need to do to one day be a rock star.

In conclusion, engaging in reflective practice is vital for optimizing the learning experience during a first empirical research project in psychology and research methods.
By following the guidance outlined above, you can develop a deeper understanding of your particular learning process, hone your research skills, and ultimately kick some butt next year with the Final Year Dissertation.
That's all we want!

\newpage

## Closing points to remember

All of the following items must be submitted:

::: {.callout-caution appearance="minimal" icon="false"}
Open Data

Open Materials

Reflective Account
:::

A really strong Mini-Dissertation submission will present these in as professional a format as the rest of the submission.

You have time to ask any questions in lab sessions or via the Discussion Forum - if you're unsure, I bet my boots somebody else is too.
