---
title: "Lecture01: Psych Science"
subtitle: "Example lecture"
date: "August 29, 2022"
footer: "[🔗 rstudio-conf-2022.github.io/teach-ds-course-website](https://rstudio-conf-2022.github.io/teach-ds-course-website)"
logo: "/images/brain2.png"
categories: "Lecture"
format: 
  pdf: default
  html: default
  revealjs: default
---

# Welcome!

@bird2010

who says [@wright201]

## CSS Tests

[shout]{.shout} [question]{.question} [takeaway]{.takeaway}

[quote-source]{.quote-source}

[midi]{.midi}

[large]{.large}

::: calloutphoto
kapow!!
:::

::: callout-tweet
Tweet from the callout tweet
:::

::: callout-tweet
Tweet from the callout tweet
:::

::: {.callout-tweet .icon}
Tweet from the callout tweet with icon
:::

::: callout-tip
Some wild callout
:::

::: callout-warning
Some wild callout
:::

## another page

Here are my tests of callout blocks.

See the
[documentation](https://quarto.org/docs/authoring/callouts.html).

::: callout-note
Note that there are five types of callouts, including: `note`,
`warning`, `important`, `tip`, and `caution`.
:::

::: callout-warning
Don't do that! simple appearance.
:::

::: callout-important
Do do this!
:::

## continued

::: callout-tip
## Tip With Caption

This is an example of a callout with a caption.
:::

::: {.callout-caution collapse="true"}
## Expand To Learn About Collapse

This is an example of a 'folded' caution callout that can be expanded by
the user. You can use `collapse="true"` to collapse it by default or
`collapse="false"` to make a collapsible callout that is expanded by
default.
:::

::: {.callout-caution appearance="simple"}
Don't do that! simple appearance.
:::

::: {.callout-caution appearance="minimal"}
Don't do that! minimal appearance.
:::

## clean templates

## Example slide {.refbox}

### This is a subtitle

Here we have some text that may run over several lines of the slide
frame, depending on how long it is.

-   first item
    -   A sub item

Next, we'll brief review some theme-specific components.

-   Note that *all* of the standard Reveal.js
    [features](https://quarto.org/docs/presentations/revealjs/) can be
    used with this theme, even if we don't highlight them here.

## Additional theme classes {.footerbox}

### Some extra things you can do with the clean theme

Special classes for emphasis

-   `.alert` class for default emphasis, e.g. [important note]{.alert}.
-   `.fg` class for custom colour, e.g. [important note]{.fg
    style="--col: #e64173"}.
-   `.bg` class for custom background, e.g. [important note]{.bg
    style="--col: #e64173"}.

Cross-references

-   `.button` class provides a Beamer-like button, e.g.
    [[Summary](#sec-summary)]{.button}

## Want more? {.quotebox-opaque}

## slide {.quotebox-transparent-bottom-right}

::: cleft
text - div cleft
:::

::: cright
text - div cright
:::

### See our longer demo slides {.quotebox-transparent}

We've deliberarely kept this template lean, to get you up and running as
fast as possible.

We provide a separate [demo
template](https://github.com/grantmcdermott/quarto-revealjs-clean-demo),
with more examples for integrating code, tables, figures, etc.

-   See the live demo slides
    [here](https://grantmcdermott.com/quarto-revealjs-clean-demo/template.html).

## Summary {#sec-summary}

### A minimal and elegant presentation theme

The Quarto reveal.js clean theme aims to be a minimal and elegant
presention theme.

Install the theme.

``` bash
quarto install extension grantmcdermott/quarto-revealjs-clean
```

Use this lean template.

``` bash
quarto use template grantmcdermott/quarto-revealjs-clean
```

Use the longer demo template.

``` bash
quarto use template grantmcdermott/quarto-revealjs-clean-demo
```

## Bullet point list

**Unordered**

-   Item A
-   Item B
-   Item C

**Ordered**

1.  Item 1
2.  Item 2
3.  Item 3

## Incremental list

::: incremental
-   Item 1
-   Item 2
-   Item 3
:::

## Equations

Write mathematical symbols and equations using Latex.

::: callout-note
Vallout note
:::

## Columns as normal

::: columns
::: {.column width="40%"}
Left column
:::

::: {.column width="60%"}
Right column
:::
:::

## Columns 2

::: columns
::: {.column width="70%"}
I would like to have text here

Sentence becomes longer, it should automatically stay in their column
:::

::: {.column width="30%"}
and here

More text
:::
:::

## Columns 3 {classoption="twocolumn"}

monkeys

puppies

## Themes {classoption="twocolumn"}

Customize the appearance of the slides using

-   Built-in [Reveal
    theme](https://quarto.org/docs/presentations/revealjs/themes.html#using-themes)

-   Modify built-in theme using
    [Sass](https://quarto.org/docs/presentations/revealjs/themes.html#creating-themes)

    -   Variant of CSS that supports variables and other features

-   Create custom thing using Sass

Specify the theme and/or Sass file (.scss) in the YAML

## Refs

## takeaway {.takeaway}

just stuff

## takeaway

just stuff {.takeaway}

## Quoteboxes {.quotebox-transparent}

::: quotebox-transparent-low
quoteboxt
:::

quoteboxtl

## cleft cright

Here's some good old text

::: cleft
cleft stuff Gullibility has started to be studied due to the fact it
gives valuable insights into human behaviour, cognition, and
decision-making processes. Gullibility study has practical applications
within different fields, such as psychology, sociology, marketing, and
public policy. The study of factors affecting gullibility has also been
conducted to create a precise psychological profile of individuals prone
to being gullible. Therefore, emotional intelligence (Baker et al.,
2013; Young et al., 2015), social intelligence (Hart et al., 2021;
Teunisse et al., 2020) trust (Baker et al., 2013; Hamby et al., 2021;
Rotter, 1967; Rotter, 1980; Teunisse et al., 2020: Yamagishi et al.,
1999), personality factors (Begue et al., 2015; George et al., 2020;
Gore et al., 2012; Peace et al., 2011; Teunisse et al., 2020), facial
representation (Jaeger & Meral, 2022) and overall poor decision-making
mechanisms have been included. The benefit of studying gullibility lies
in the need to determine and safeguard individuals who are likely to
fall for deceptive speech, online as well as face to face.
:::

::: cright
cright stuff

trust (Baker et al., 2013; Hamby et al., 2021; Rotter, 1967; Rotter,
1980; Teunisse et al., 2020: Yamagishi et al., 1999), personality
factors (Begue et al., 2015; George et al., 2020; Gore et al., 2012;
Peace et al., 2011; Teunisse et al., 2020), facial representation
(Jaeger & Meral, 2022) and overall poor decision-making mechanisms have
been included. The benefit of studying gullibility lies in the need to
determine and safeguard individuals who are likely to fall for deceptive
speech, online as well as face to face.
:::
