---
title: "Prepare for Week 01: <br> Replace it!"
subtitle: "This is a meaningful subtitle"
author: 
  - name: "Dr. Gordon Wright"
    orcid: 0000-0001-9424-5743
    email: g.wright@gold.ac.uk
date: "10/02/2023"
date-format: long
license: "CC BY-NC-SA"
footer: "[🔗 VLE](https://www.bbc.co.uk)"
citations-hover: true
categories: 
  - "Prep"
  - "Week 1"
params:
  class: "prep01"
listing:
  contents:
    - "lectures/*.qmd"
    - "labs/*reports.qmd"
# listing:
#   - id: lecture-listing
#     contents:
#       - content/lectures/lec01.qmd
#     type: table
#     fields: [title, date, image]
#     date-format: "ddd, MMM DD"
#     field-display-names:
#       title: "Topic"
#       date: "Date"
#     sort: [filename]
#     sort-ui: false
#     filter-ui: false
#   - id: lab-listing
#     contents:
#       - content/labs/lab01.qmd
#     type: table
#     fields: [title, date, image]
#     date-format: "ddd, MMM DD"
#     field-display-names:
#       title: "Title"
#       date: "Date"
#     sort: [date]
#     sort-ui: false
#     filter-ui: false  
#   - id: readings-listing
#     contents:
#       - content/readings/read01.qmd
#       # - ../labs/Lab01.qmd
#     type: table
#     fields: [title, date, image]
#     date-format: "ddd, MMM DD"
#     field-display-names:
#       categories: "Readings"
#       title: "Title"
#       date: "Due"
#     sort: [date]
#     sort-ui: false
#     filter-ui: false
#   - id: minidiss-listing
#     contents:
#       - content/minidiss/minidiss01.qmd
#       # - ../labs/Lab01.qmd
#     type: table
#     fields: [title, subtitle, image]
#     date-format: "ddd, MMM DD"
#     field-display-names:
#       categories: "MiniDiss"
#       title: "Title"
#       subtitle: "Topic"
#     sort: [date]
#     sort-ui: false
#     filter-ui: false
# tbl-colwidths: [10,50,40]
format: 
  # pdf: default
  # pptx: default
  html: default
  # docx: default
  # revealjs: 
  #   header-logo: "/images/rmlogo.png"
  #   header: "Research Methods Lab 01 - Short Title" # Replace it
  #   hide-from-titleSlide: "text"
filters:
  - reveal-header
execute:
 echo: false
 freeze: auto
embed-resources: true
  # Title page populated by content above
---

# Week 01

```{=html}

<iframe src="https://ps52007d.littlemonkeylab.com/lectures/lec00.slides.html" title="Induction Week Lecture" width="960" height="500" data-external="1"></iframe>
```
## Introduction & Lecture Preview

::: {#lecture-listing}
:::

::: {.callout .primary}
**Key Focus:** Briefly describe the key focus of this week's lecture.
:::

{{< include week1listing.qmd >}}

-   **Important Points:**
    1.  Point 1
    2.  Point 2
-   **Preparatory Reading or Reflection:**
    -   [Reading 1](#)
    -   [Reading 2](#)

::: {#readings-listing}
:::

------------------------------------------------------------------------

{{< include week1listing.qmd >}}

::: {#lab-listing}
:::

## Lab Sessions

### Checklist of Progress

-   [ ] Task 1
-   [ ] Task 2

### Ideas for Team Coordination

::: card
**Suggested Activity:** Describe a team-building exercise or
coordination tip.
:::

### Key Focus of the Week

-   Reading: [Lab Manual, Chapter X](#)
-   Tools/Guides: [Tool 1](#), [Tool 2](#)

------------------------------------------------------------------------

## CHIP Topics {#CHIPTopics}

::: callout-important
## CHIP Topic(s)

Reflection Topic: Insert conceptual or historical issues for reflection
and possible follow-up.

[link to resource](www.bbc.co.uk){#CHIPLINK}

[Review CHIP Coursework Requirements](www.bbc.co.uk){.btn .btn-info .btn
role="button"} [See all CHIP Topics covered to date](www.bbc.co.uk){.btn
.btn-success .btn role="button"}
:::

|                                                                        |
|:-----------------------------------------------------------------------|
| ::: {#minidiss-listing} ::: \## Mini-Dissertation Skills & Checkpoints |
| \- **Activity 1**: Description - **Activity 2**: Description           |

## Tips, Hacks, and Guides

::: card
**Employability Tip:** Insert tip for boosting employability.
:::

-   **Fun Stuff**: Describe fun activities or games.

------------------------------------------------------------------------

## Save The Date {{< fa calendar >}}

::: {.callout .info}
**Upcoming Events:** Describe any upcoming activities or events that
might be of interest.
:::

| Shortcode                                          | Icon                                    |
|----------------------------------------------------|-----------------------------------------|
| `{{{< fa thumbs-up >}}}`                           | {{< fa thumbs-up >}}                    |
| `{{{< fa folder >}}}`                              | {{< fa folder >}}                       |
| `{{{< fa chess-pawn >}}}`                          | {{< fa chess-pawn >}}                   |
| `{{{< fa brands bluetooth >}}}`                    | {{< fa brands bluetooth >}}             |
| `{{{< fa brands twitter size=2xl >}}}` (HTML only) | {{< fa brands twitter size=2xl >}}      |
| `{{{< fa brands github size=5x >}}}` (HTML only)   | {{< fa brands github size=5x >}}        |
| `{{{< fa battery-half size=Huge >}}}`              | {{< fa battery-half size=Huge >}}       |
| `{{{< fa envelope title="An envelope" >}}}`        | {{< fa envelope title="An envelope" >}} |

{{< fa thumbs-up >}}
